'use strict';function p(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
function r(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var t=r(this);function v(a,b){if(b)a:{var d=t;a=a.split(".");for(var f=0;f<a.length-1;f++){var k=a[f];if(!(k in d))break a;d=d[k]}a=a[a.length-1];f=d[a];b=b(f);b!=f&&null!=b&&q(d,a,{configurable:!0,writable:!0,value:b})}}
v("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new d(f+(l||"")+"_"+k++,l)}function d(l,c){this.g=l;q(this,"description",{configurable:!0,writable:!0,value:c})}if(a)return a;d.prototype.toString=function(){return this.g};var f="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",k=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var f=t[b[d]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&q(f.prototype,a,{configurable:!0,writable:!0,value:function(){return w(p(this))}})}return a});function w(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function x(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:p(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function y(a){if(!(a instanceof Array)){a=x(a);for(var b,d=[];!(b=a.next()).done;)d.push(b.value);a=d}return a}function z(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.o=0;this.j=null}function A(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}
z.prototype.m=function(a){this.i=a};function B(a,b){a.j={F:b,G:!0};a.g=a.o}z.prototype.return=function(a){this.j={return:a};this.g=this.o};function C(a,b,d){a.g=d;return{value:b}}function D(a){this.g=new z;this.h=a}function E(a,b){A(a.g);var d=a.g.h;if(d)return F(a,"return"in d?d["return"]:function(f){return{value:f,done:!0}},b,a.g.return);a.g.return(b);return J(a)}
function F(a,b,d,f){try{var k=b.call(a.g.h,d);if(!(k instanceof Object))throw new TypeError("Iterator result "+k+" is not an object");if(!k.done)return a.g.l=!1,k;var l=k.value}catch(c){return a.g.h=null,B(a.g,c),J(a)}a.g.h=null;f.call(a.g,l);return J(a)}function J(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(d){a.g.i=void 0,B(a.g,d)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.G)throw b.F;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function K(a){this.next=function(b){A(a.g);a.g.h?b=F(a,a.g.h.next,b,a.g.m):(a.g.m(b),b=J(a));return b};this.throw=function(b){A(a.g);a.g.h?b=F(a,a.g.h["throw"],b,a.g.m):(B(a.g,b),b=J(a));return b};this.return=function(b){return E(a,b)};this[Symbol.iterator]=function(){return this}}function L(a){function b(f){return a.next(f)}function d(f){return a.throw(f)}return new Promise(function(f,k){function l(c){c.done?f(c.value):Promise.resolve(c.value).then(b,d).then(l,k)}l(a.next())})}
function M(a){return L(new K(new D(a)))}function N(){for(var a=Number(this),b=[],d=a;d<arguments.length;d++)b[d-a]=arguments[d];return b}
v("Promise",function(a){function b(c){this.h=0;this.i=void 0;this.g=[];this.o=!1;var e=this.j();try{c(e.resolve,e.reject)}catch(g){e.reject(g)}}function d(){this.g=null}function f(c){return c instanceof b?c:new b(function(e){e(c)})}if(a)return a;d.prototype.h=function(c){if(null==this.g){this.g=[];var e=this;this.i(function(){e.l()})}this.g.push(c)};var k=t.setTimeout;d.prototype.i=function(c){k(c,0)};d.prototype.l=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var e=0;e<c.length;++e){var g=
c[e];c[e]=null;try{g()}catch(h){this.j(h)}}}this.g=null};d.prototype.j=function(c){this.i(function(){throw c;})};b.prototype.j=function(){function c(h){return function(m){g||(g=!0,h.call(e,m))}}var e=this,g=!1;return{resolve:c(this.A),reject:c(this.l)}};b.prototype.A=function(c){if(c===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.C(c);else{a:switch(typeof c){case "object":var e=null!=c;break a;case "function":e=!0;break a;default:e=!1}e?this.v(c):this.m(c)}};
b.prototype.v=function(c){var e=void 0;try{e=c.then}catch(g){this.l(g);return}"function"==typeof e?this.D(e,c):this.m(c)};b.prototype.l=function(c){this.u(2,c)};b.prototype.m=function(c){this.u(1,c)};b.prototype.u=function(c,e){if(0!=this.h)throw Error("Cannot settle("+c+", "+e+"): Promise already settled in state"+this.h);this.h=c;this.i=e;2===this.h&&this.B();this.H()};b.prototype.B=function(){var c=this;k(function(){if(c.I()){var e=t.console;"undefined"!==typeof e&&e.error(c.i)}},1)};b.prototype.I=
function(){if(this.o)return!1;var c=t.CustomEvent,e=t.Event,g=t.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):"function"===typeof e?c=new e("unhandledrejection",{cancelable:!0}):(c=t.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.i;return g(c)};b.prototype.H=function(){if(null!=this.g){for(var c=0;c<this.g.length;++c)l.h(this.g[c]);this.g=null}};var l=new d;b.prototype.C=
function(c){var e=this.j();c.s(e.resolve,e.reject)};b.prototype.D=function(c,e){var g=this.j();try{c.call(e,g.resolve,g.reject)}catch(h){g.reject(h)}};b.prototype.then=function(c,e){function g(n,u){return"function"==typeof n?function(G){try{h(n(G))}catch(H){m(H)}}:u}var h,m,I=new b(function(n,u){h=n;m=u});this.s(g(c,h),g(e,m));return I};b.prototype.catch=function(c){return this.then(void 0,c)};b.prototype.s=function(c,e){function g(){switch(h.h){case 1:c(h.i);break;case 2:e(h.i);break;default:throw Error("Unexpected state: "+
h.h);}}var h=this;null==this.g?l.h(g):this.g.push(g);this.o=!0};b.resolve=f;b.reject=function(c){return new b(function(e,g){g(c)})};b.race=function(c){return new b(function(e,g){for(var h=x(c),m=h.next();!m.done;m=h.next())f(m.value).s(e,g)})};b.all=function(c){var e=x(c),g=e.next();return g.done?f([]):new b(function(h,m){function I(G){return function(H){n[G]=H;u--;0==u&&h(n)}}var n=[],u=0;do n.push(void 0),u++,f(g.value).s(I(n.length-1),m),g=e.next();while(!g.done)})};return b});
v("String.prototype.startsWith",function(a){return a?a:function(b,d){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var f=this.length,k=b.length;d=Math.max(0,Math.min(d|0,this.length));for(var l=0;l<k&&d<f;)if(this[d++]!=b[l++])return!1;return l>=k}});var O=new BroadcastChannel("projectChannel");function P(){return M(function(a){return 1==a.g?C(a,navigator.serviceWorker.getRegistrations(),2):a.return(a.i.filter(function(b){return b.scope.startsWith(location.origin)}))})}function Q(){var a=R;return M(function(b){if(1==b.g)return C(b,P(),2);b.i.forEach(function(d){return M(function(f){a.log("Unregistering service worker",d);return C(f,d.unregister(),0)})});b.g=0})}
function S(){var a=R;return M(function(b){a.log("Sending shutdown message to all service workers listening on the Project Channel");O.postMessage({type:"STOP"});b.g=0})}function T(){var a=R,b;return M(function(d){if(1==d.g)return C(d,P(),2);b=d.i;a.log("There are "+b.length+" service workers registered with this tab",b);return d.return(b.length)})}function U(a){M(function(b){a.log("Service worker is active. Feel free to start doing stuff");O.postMessage({type:"START"});b.g=0})}
function V(){var a=R;return M(function(b){a.log("Listening for messages on the Project Channel");O.addEventListener("message",function(d){a.log("Incoming "+d.data.type+" message",d);switch(d.data.type){case "SERVICE_WORKER_ACTIVE":U(a);break;default:throw Error("Unexpected message type "+d.data.type);}});b.g=0})}function W(){var a=R;navigator.serviceWorker&&navigator.serviceWorker.addEventListener("controllerchange",function(b){a.log("The service worker controlling this tab has changed",b)})};function X(){}X.prototype.g=function(a){var b=N.apply(1,arguments);b=["%cProject Service Null Loader","color: white; background-color: black; border: 1px solid white; padding: 4px"].concat(y(b));switch(a){case "log":console.log.apply(console,y(b));break;case "warn":console.warn.apply(console,y(b));break;case "error":console.error.apply(console,y(b));break;default:throw Error("Encountered unhandled method: "+a);}};X.prototype.log=function(){this.g.apply(this,["log"].concat(y(N.apply(0,arguments))))};
X.prototype.error=function(){this.g.apply(this,["error"].concat(y(N.apply(0,arguments))))};X.prototype.h=function(){this.g.apply(this,["warn"].concat(y(N.apply(0,arguments))))};var R=new X;(function(){var a;return M(function(b){switch(b.g){case 1:R.log("Google Patents Service Workers are disabled");if(!navigator.serviceWorker){R.h("JavaScript Service Workers are not available in the current browser tab, so the main Patents app has not been able to look for registered service workers.");b.g=0;break}W();return C(b,T(),3);case 3:a=b.i;if(!(0<a)){b.g=0;break}return C(b,V(),5);case 5:return C(b,S(),6);case 6:return C(b,Q(),7);case 7:location.reload(),b.g=0}})})();
